### PR TITLE
Improvements to the queue metrics docs

### PR DESCRIPTION
**Pull request by edsko**
In response to https://issues.serokell.io/issue/CSL-1651 .

### CODE REVIEW

**Comment by domenkozar** [comment]
Cc @jmitchell

**Comment by jmitchell** [comment]
LGTM. Thanks, @edsko.

**Comment by domenkozar** [comment]
What's the status here?

**Comment by jmitchell** [comment]
@edsko, I lack permissions to merge or update this branch. Can you push this along? Thanks.

**Comment by edsko** [comment]
Rebased. This is a very minor docs improvement. @dcoutts asked for your review for policy's sake, but feel free to merge whenever.

**Pull request merged**
