### PR TITLE
[TW-148] outbound queueing

### PR DESCRIPTION
**Pull request by avieth**
Includes Edsko's work on a complex outbound queueing mechanism. It's been modified so that it can fulfill the abstract `OutboundQueue` interface.

https://github.com/input-output-hk/cardano-sl/pull/1116

### CODE REVIEW

**Comment by avieth** [comment]
@dcoutts ready for review. Most of it is @edsko 's work.

**Comment by avieth** [comment]
CI timed out before it even began to build time-warp-nt...

**Comment by avieth** [comment]
> CI timed out before it even began to build time-warp-nt...

Perhaps the addition of aeson brings in too many dependencies

**Comment by avieth** [comment]
Ok ready to merge. Waiting for approval from @dcoutts and/or @georgeee

**Comment by edsko** [comment]
> The result 'Map' values are each an action to wait for the conversation to be completed. They return the conversation result or throw an exception if the conversation itself failed.

> This way, if you ignore the 'Map' result then the enqueue is asynchronous, but if you traverse the Map results then it is of course synchronous.

Is that really true?

**Pull request merged**
