### PR TITLE
add the "bucketSpareCapacity" function

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
This simple PR adds a new function called `bucketSpareCapacity` to be used to query an `OutboundQueue` regarding the "free slots" it has to accept more peers. It can be used by application code to implement services to check if we hit our subscription limit for a particular <queue, bucket> combination.

cc @edsko @dcoutts @avieth

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
> Using 'Nothing' to mean 'As much as you like' is a bit confusing semantically though

I do agree! Any suggestion? I guess we could create a separate type like:

```haskell
data BucketCapacity = CapacityUnlimited
                                    |  BucketCapacity !Int
```

It would act essentially as a non-polymorphic version of `Maybe a`, but with a more precise semantic. I'm easy!

**Comment by edsko** [comment]
It doesn't really return the capacity though, does it? It returns _spare_ capacity?

**Comment by adinapoli-iohk** [comment]
> It returns spare capacity?

Correct. So I guess we either name the type appropriately (I suck at names!) or we simply stick with the status quo (`Maybe`) :)

**Comment by edsko** [comment]
How about

``` haskell
data SpareCapacity = SpareCapacity Int | UnlimitedCapacity
```

:)

**Comment by adinapoli-iohk** [comment]
Do like! :)

**Comment by adinapoli-iohk** [comment]
@edsko ok, it should be semantically less confusing now! 😛

**Pull request merged**
