### PR TITLE
[CSL-738] (WIP) Simplify constraints in NTP

### PR DESCRIPTION
**Pull request by Martoon-00**
Cherry-picked from `master`

### CODE REVIEW

**Comment by gromakovsky** [comment]
And now I think it should go to `time-warp-nt-0.1-csl` :)

Ideally such situation shouldn't happen, but some bardaq is happening currently, so it's a workaround.

**Comment by Martoon-00** [comment]
Close once `time-warp-nt-0.1-csl` gets merged here

**Comment by avieth** [comment]
@Martoon-00 ok to close this?

**Comment by Martoon-00** [comment]
Since we have it `master`, let's close. Sorry for this mess

**Pull request closed without merging**
